/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package evaluacion3;

import com.sun.source.util.TaskEvent;
import java.sql.SQLException;

/**
 *
 * @author cetecom
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lobbyButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cuotaMensualTextField = new javax.swing.JTextField();
        appTextField = new javax.swing.JTextField();
        apmTextField = new javax.swing.JTextField();
        tallerLabel = new javax.swing.JLabel();
        dInscLabel = new javax.swing.JLabel();
        cuotaMensuallabel = new javax.swing.JLabel();
        apmLabel = new javax.swing.JLabel();
        appLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        rutTextField = new javax.swing.JTextField();
        rutLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        diasInsComboBox = new javax.swing.JComboBox<>();
        resultLabel = new javax.swing.JLabel();
        limpiarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        tallerComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lobbyButton.setBackground(new java.awt.Color(0, 0, 0));
        lobbyButton.setForeground(new java.awt.Color(255, 255, 255));
        lobbyButton.setText("Volver");
        lobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobbyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lobbyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 532, -1, 36));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 210, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evaluacion3/gymblck.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, 250));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel4.setText("|");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 330, 70));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BlackHouse");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 330, 70));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setText("|");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 330, 70));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel7.setText("|");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 330, 70));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setText("Inscripción");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        cuotaMensualTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuotaMensualTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(cuotaMensualTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 135, -1));

        appTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(appTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 135, -1));

        apmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apmTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(apmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 135, -1));

        tallerLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tallerLabel.setText("Taller:");
        tallerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tallerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        dInscLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dInscLabel.setText("Dias de Inscripción:");
        dInscLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(dInscLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        cuotaMensuallabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cuotaMensuallabel.setText("Cuota Mensual:");
        cuotaMensuallabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(cuotaMensuallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        apmLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        apmLabel.setText("Apellido Materno:");
        apmLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(apmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        appLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appLabel.setText("Apellido Paterno:");
        appLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(appLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 135, -1));

        rutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(rutTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 135, -1));

        rutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rutLabel.setText("Rut:");
        jPanel2.add(rutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");
        nombreLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        diasInsComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        diasInsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "90", "180" }));
        jPanel2.add(diasInsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 140, -1));
        jPanel2.add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        limpiarButton.setBackground(new java.awt.Color(0, 0, 0));
        limpiarButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        limpiarButton.setForeground(new java.awt.Color(255, 255, 255));
        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 170, 60));

        agregarButton.setBackground(new java.awt.Color(0, 0, 0));
        agregarButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        agregarButton.setForeground(new java.awt.Color(255, 255, 255));
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 170, 60));

        tallerComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tallerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karate", "Judo", "Kung-fu", "Boxeo", "Jiu-jitsu", "Capoeira", "Muay Thai", "Krav Maga", "Kendo", "Aikido", "Taekwondo", "Esgrima" }));
        jPanel2.add(tallerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTextFieldActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void appTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appTextFieldActionPerformed

    private void apmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apmTextFieldActionPerformed
        // TODO add your handling code here: abajo va el combo box 
    }//GEN-LAST:event_apmTextFieldActionPerformed

    private void cuotaMensualTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuotaMensualTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuotaMensualTextFieldActionPerformed

    private void lobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lobbyButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Lobby().setVisible(true);
    }//GEN-LAST:event_lobbyButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        // TODO add your handling code here:
        rutTextField.setText("");
        nombreTextField.setText("");
        appTextField.setText("");
        apmTextField.setText("");
        tallerComboBox.setSelectedIndex(0);
        diasInsComboBox.setSelectedIndex(0);
        cuotaMensualTextField.setText("");
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        // TODO add your handling code here:
        if (rutTextField.getText().isEmpty() || nombreTextField.getText().isEmpty() || appTextField.getText().isEmpty()
                || apmTextField.getText().isEmpty() || cuotaMensualTextField.getText().isEmpty()) {
            resultLabel.setText("Hay campos vacios, procura llenar todos los campos con información.");
        } else {
            String sql1 = "insert into miembro values(Null, '" + rutTextField.getText() + "', '"
                    + nombreTextField.getText() + "', '"
                    + appTextField.getText() + "', '"
                    + apmTextField.getText() + "', '"
                    + tallerComboBox.getSelectedItem().toString()+ "', "
                    + diasInsComboBox.getSelectedItem().toString() + ", "
                    + cuotaMensualTextField.getText()
                    + ");";
            
            try {
                Lobby.st.executeUpdate(sql1);
                resultLabel.setText("Usuario Actualizado correctamente!");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                resultLabel.setText("Ha ocurrido un error, revisa la consola.");
            }
        }
    }//GEN-LAST:event_agregarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JLabel apmLabel;
    private javax.swing.JTextField apmTextField;
    private javax.swing.JLabel appLabel;
    private javax.swing.JTextField appTextField;
    private javax.swing.JTextField cuotaMensualTextField;
    private javax.swing.JLabel cuotaMensuallabel;
    private javax.swing.JLabel dInscLabel;
    private javax.swing.JComboBox<String> diasInsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton lobbyButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rutLabel;
    private javax.swing.JTextField rutTextField;
    private javax.swing.JComboBox<String> tallerComboBox;
    private javax.swing.JLabel tallerLabel;
    // End of variables declaration//GEN-END:variables
}
