/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package evaluacion3;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CETECOM
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lobbyButton = new javax.swing.JButton();
        cargarButton = new javax.swing.JButton();
        cuotaMensualTextField = new javax.swing.JTextField();
        appTextField = new javax.swing.JTextField();
        apmLabel = new javax.swing.JLabel();
        apmTextField = new javax.swing.JTextField();
        tallerLabel = new javax.swing.JLabel();
        rutLabel = new javax.swing.JLabel();
        dInscLabel = new javax.swing.JLabel();
        rutTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        cuotaMensuallabel = new javax.swing.JLabel();
        appLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        limpiarButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        diasInsComboBox = new javax.swing.JComboBox<>();
        modificar2 = new javax.swing.JButton();
        tallerComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lobbyButton.setBackground(new java.awt.Color(0, 0, 0));
        lobbyButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lobbyButton.setForeground(new java.awt.Color(255, 255, 255));
        lobbyButton.setText("Volver");
        lobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobbyButtonActionPerformed(evt);
            }
        });
        jPanel2.add(lobbyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, 36));

        cargarButton.setBackground(new java.awt.Color(0, 0, 0));
        cargarButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cargarButton.setForeground(new java.awt.Color(255, 255, 255));
        cargarButton.setText("Cargar");
        cargarButton.setPreferredSize(new java.awt.Dimension(200, 60));
        cargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cargarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 100, 30));

        cuotaMensualTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuotaMensualTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(cuotaMensualTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 135, -1));

        appTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(appTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 135, -1));

        apmLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        apmLabel.setText("Apellido Materno:");
        apmLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(apmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        apmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apmTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(apmTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 135, -1));

        tallerLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tallerLabel.setText("Taller:");
        tallerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tallerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        rutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rutLabel.setText("Rut:");
        jPanel2.add(rutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        dInscLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dInscLabel.setText("Dias de Inscripción:");
        dInscLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(dInscLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        rutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(rutTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 135, -1));

        nombreLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");
        nombreLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 135, -1));

        cuotaMensuallabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cuotaMensuallabel.setText("Cuota Mensual:");
        cuotaMensuallabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(cuotaMensuallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        appLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        appLabel.setText("Apellido Paterno:");
        appLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(appLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificarciòn");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 110, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 210, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evaluacion3/gymblck.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 250));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel4.setText("|");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 330, 70));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BlackHouse");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 330, 70));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setText("|");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 330, 70));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel7.setText("|");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 330, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ingresa el Rut y de a \"Buscar\" para cargar la información");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        limpiarButton.setBackground(new java.awt.Color(0, 0, 0));
        limpiarButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        limpiarButton.setForeground(new java.awt.Color(255, 255, 255));
        limpiarButton.setText("Limpiar");
        limpiarButton.setPreferredSize(new java.awt.Dimension(200, 60));
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 150, -1));
        jPanel2.add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        diasInsComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        diasInsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "90", "180" }));
        diasInsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasInsComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(diasInsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 140, -1));

        modificar2.setBackground(new java.awt.Color(0, 0, 0));
        modificar2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        modificar2.setForeground(new java.awt.Color(255, 255, 255));
        modificar2.setText("Modificar");
        modificar2.setPreferredSize(new java.awt.Dimension(200, 60));
        modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar2ActionPerformed(evt);
            }
        });
        jPanel2.add(modificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 150, -1));

        tallerComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tallerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karate", "Judo", "Kung-fu", "Boxeo", "Jiu-jitsu", "Capoeira", "Muay Thai", "Krav Maga", "Kendo", "Aikido", "Taekwondo", "Esgrima" }));
        jPanel2.add(tallerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarButtonActionPerformed
        // TODO add your handling code here:(con un barra update)
        if (!rutTextField.getText().isEmpty()) {
            try {
                String sql = "SELECT * FROM miembro WHERE rut = '" + rutTextField.getText() + "'";

                ResultSet result = Lobby.st.executeQuery(sql);

                if (result.next()) {
                    // Obtener datos del ResultSet
                    Object rut = result.getObject(2);
                    Object nombre = result.getObject(3);
                    Object apPaterno = result.getObject(4);
                    Object apMaterno = result.getObject(5);
                    Object taller = result.getObject(6);
                    Object diasInscritosResult = result.getObject(7);
                    Object cuotaMensual = result.getObject(8);

                    nombreTextField.setText(nombre.toString());
                    appTextField.setText(apPaterno.toString());
                    apmTextField.setText(apMaterno.toString());
                    switch (taller.toString()) {
                        case "Karate":
                            tallerComboBox.setSelectedIndex(0);
                            break;
                        case "Judo":
                            tallerComboBox.setSelectedIndex(1);
                            break;
                        case "Kung-fu":
                            tallerComboBox.setSelectedIndex(2);
                            break;
                        case "Boxeo":
                            tallerComboBox.setSelectedIndex(3);
                            break;
                        case "Jiu-jitsu":
                            tallerComboBox.setSelectedIndex(4);
                            break;
                        case "Capoeira":
                            tallerComboBox.setSelectedIndex(5);
                            break;
                        case "Muay Thai":
                            tallerComboBox.setSelectedIndex(6);
                            break;
                        case "Krav Maga":
                            tallerComboBox.setSelectedIndex(7);
                            break;
                        case "Kendo":
                            tallerComboBox.setSelectedIndex(8);
                            break;
                        case "Aikido":
                            tallerComboBox.setSelectedIndex(9);
                            break;
                        case "Taekwondo":
                            tallerComboBox.setSelectedIndex(10);
                            break;
                        case "Esgrima":
                            tallerComboBox.setSelectedIndex(11);
                            break;
                        default:
                            break;
                    }
                    switch (diasInscritosResult.toString()) {
                        case "30":
                            diasInsComboBox.setSelectedIndex(0);
                            break;
                        case "90":
                            diasInsComboBox.setSelectedIndex(1);
                            break;
                        case "180":
                            diasInsComboBox.setSelectedIndex(2);
                            break;
                        default:
                            break;
                    }
                    cuotaMensualTextField.setText(cuotaMensual.toString());
                }
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_cargarButtonActionPerformed

    private void cuotaMensualTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuotaMensualTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuotaMensualTextFieldActionPerformed

    private void appTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appTextFieldActionPerformed

    private void apmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apmTextFieldActionPerformed
        // TODO add your handling code here: abajo va el combo box
    }//GEN-LAST:event_apmTextFieldActionPerformed

    private void rutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTextFieldActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void lobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lobbyButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Lobby().setVisible(true);
    }//GEN-LAST:event_lobbyButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        rutTextField.setText("");
        nombreTextField.setText("");
        appTextField.setText("");
        apmTextField.setText("");
        tallerComboBox.setSelectedIndex(0);
        diasInsComboBox.setSelectedIndex(0);
        cuotaMensualTextField.setText("");
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void diasInsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasInsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasInsComboBoxActionPerformed

    private void modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String sql = "DELETE FROM miembro WHERE rut = '" + rutTextField.getText() + "'";

        // Ejecutar la sentencia
        try {
            Lobby.st.executeUpdate(sql);
        } catch(SQLException e) {
            System.out.println(e.getMessage());
        }
        
        if (rutTextField.getText().isEmpty() || nombreTextField.getText().isEmpty() || appTextField.getText().isEmpty()
                || apmTextField.getText().isEmpty() || cuotaMensualTextField.getText().isEmpty()) {
            resultLabel.setText("Hay campos vacios, procura llenar todos los campos con información.");
        } else {
            String sql1 = "insert into miembro values(Null, '" + rutTextField.getText() + "', '"
                    + nombreTextField.getText() + "', '"
                    + appTextField.getText() + "', '"
                    + apmTextField.getText() + "', '"
                    + tallerComboBox.getSelectedItem().toString()+ "', "
                    + diasInsComboBox.getSelectedItem().toString() + ", "
                    + cuotaMensualTextField.getText()
                    + ");";
            
            try {
                Lobby.st.executeUpdate(sql1);
                resultLabel.setText("Usuario Actualizado correctamente!");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
                resultLabel.setText("Ha ocurrido un error, revisa la consola.");
            }
        }
    }//GEN-LAST:event_modificar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apmLabel;
    private javax.swing.JTextField apmTextField;
    private javax.swing.JLabel appLabel;
    private javax.swing.JTextField appTextField;
    private javax.swing.JButton cargarButton;
    private javax.swing.JTextField cuotaMensualTextField;
    private javax.swing.JLabel cuotaMensuallabel;
    private javax.swing.JLabel dInscLabel;
    private javax.swing.JComboBox<String> diasInsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton lobbyButton;
    private javax.swing.JButton modificar2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel rutLabel;
    private javax.swing.JTextField rutTextField;
    private javax.swing.JComboBox<String> tallerComboBox;
    private javax.swing.JLabel tallerLabel;
    // End of variables declaration//GEN-END:variables
}
